language: java
jdk:
  - openjdk8
before_install:
  - "echo skipped"
install:
  - "echo skipped"
script:
  - mvn install -Dmaven.javadoc.skip=true

after_success:
  bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - lpwork@foxmail.com
  slack:
    on_success: change
    on_failure: always